version: "3.1"
services:
  jenkins:
    build:
      context: ./
    restart: unless-stopped
    environment:
      - "JAVA_OPTS=-Xmx3g -Xms2G"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home
    ports:
      - "8080:8080"
      - "8081:50000"
volumes:
  jenkins-data:
    external: false